### ISSUE TITLE
Hey dude, you pushed a private key

### ISSUE THREAD

**Issue by coolnickname** [xeniorn/ExperimentsDatabase#2]
It's an auth key for eLabJournal, and it still works.
I recommend you remove it or go into eLab and disactivate it there, but if you feel like living on the edge you could also just leave it :P

https://github.com/xeniorn/ExperimentsDatabase/blob/834b5f545d8740dba052efad20278759a0dcb150/eLabJournalAPI/Main.vb#L238

**Comment by xeniorn** [comment]
Whoa. Crap. Thanks for the heads-up man. :) Just out of curiosity - how did you run into this?

**Comment by coolnickname** [comment]
I was searching on Github to see if anyone has figured out the API call to update the text in a section yet. I'm pretty sure it exists, but it's just not documented 🤔
